### ISSUE TITLE
rintrojs Help windows

### ISSUE THREAD

**Issue by philstraforelli** [kevinrue/isee-shiny-contest#1]
First of all congratulations on winning Rstudio's Shiny contest!

This is more of a "how-to" question than any sort of issue. How did you set up the first couple of windows/pages of `rintrojs::introBox()` ?

![Capture](https://user-images.githubusercontent.com/22040238/56386870-bbe94280-61d7-11e9-96d0-8d646f95944d.PNG)

All the examples I see have the `introBox()` function wrapped around a UI object, but not those two, and I would like to implement a similar process in an app I'm putting together.

Thanks in advance for your help!

**Comment by federicomarini** [comment]
Hi Phil,
I think a possible answer can be found here: https://github.com/csoneson/iSEE/blob/master/inst/extdata/intro_firststeps.txt
+
https://github.com/csoneson/iSEE/blob/f9b7b09771bb72d03d96dcc863eec90b04474f96/R/iSEE-main.R#L397-408

We did not use an `introBox` wrapper, but went for the tour where we define a `data.frame` (which we read in from a text file). This is easier to maintain when the number of steps (and elements) grows.

For the "center" placement: de facto, you just need to pick a name of an object that is _not_ present in the UI. It can be basically any string. 

Thanks for the interest, I look forward to seeing the tour in action in your app!
Federico

**Comment by philstraforelli** [comment]
Thanks for the quick response Federico! Sadly, my project is related to my employment and won't be made public.
